name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_ORIGIN: ${{ secrets.ORIGIN }}
        envkey_DOMAIN: ${{ secrets.DOMAIN }}
        envkey_PORT: ${{ secrets.PORT }}
        envkey_DB_USER: ${{ secrets.DB_USER }}
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_DB_HOST: ${{ secrets.DB_HOST }}
        envkey_DB_PORT: ${{ secrets.DB_PORT }}
        envkey_DB_NAME: ${{ secrets.DB_NAME }}
        envkey_JWT_SECRET: ${{ secrets.JWT_SECRET }}
        file_name: .env.production

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: faridzam/faculty_digital-backend-test

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - name: Pull and run docker image
      id: deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        passphrase: ${{secrets.SSH_PASSPHRASE}}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          docker pull faridzam/faculty_digital-backend-test:master
          docker stop faculty_digital-backend-test
          docker rm faculty_digital-backend-test
          docker container run -d \
          --restart always \
          --name faculty_digital-backend-test \
          -p 8002:8002 \
          -e ORIGIN=${{secrets.ORIGIN}} \
          -e DOMAIN=${{secrets.DOMAIN}} \
          -e PORT=${{secrets.PORT}} \
          -e DB_USER=${{secrets.DB_USER}} \
          -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
          -e DB_HOST=${{secrets.DB_HOST}} \
          -e DB_PORT=${{secrets.DB_PORT}} \
          -e DB_NAME=${{secrets.DB_NAME}} \
          -e JWT_SECRET=${{secrets.JWT_SECRET}} \
          faridzam/faculty_digital-backend-test:master